version: "3"

services:
    proxy:
        build: .docker/proxy
        ports:
            - 80:80
        depends_on:
          - "test-video-api.loc"
          - "test-video.loc"

    db:
        image: mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test-video
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 43306:3306
            - 43060:33060

    php-api:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: php-api
        volumes:
            - ./api/:/var/www/symfony/
        depends_on:
            - db
        ports:
            - 9000:9000

    php-auth:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: php-auth
        volumes:
            - ./auth/:/var/www/symfony/
        ports:
            - 10000:9000

    "test-video-api.loc":
        build: .docker/test-video-api
        container_name: "test-video-api.loc"
        ports:
            - 11080:11080
        volumes:
            - ./api/:/var/www/symfony/
        depends_on:
            - php-api

    "test-video.loc":
        build: .docker/test-video
        container_name: "test-video.loc"
        ports:
            - 12080:12080
        volumes:
            - ./auth/:/var/www/symfony/
        depends_on:
            - "test-video-api.loc"
            - php-auth
