version: "3.7"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    db:
        image: mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
        ports:
            - 43306:3306
            - 43060:33060

    php:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www/symfony
        depends_on:
            - db
        ports:
            - 9000:9000

    api:
        build: .docker/api
        ports:
            - 20080:80
            - 20443:443
        volumes:
            - ./:/var/www/symfony
        environment:
            VIRTUAL_HOST: api.local
        depends_on:
            - php

    auth:
        build: .docker/auth
        ports:
            - 21080:80
            - 21443:443
        volumes:
            - ./:/var/www/symfony
        environment:
            VIRTUAL_HOST: auth.local
        depends_on:
            - api
            - php

networks:
    default:
        external:
            name: nginx-proxy
